import { describe, expect, test } from "bun:test";
import { createUuidV7 } from "../ids/uuid-v7";

describe("createUuidV7", () => {
  test("generates RFC-shaped version 7 UUIDs", () => {
    const id = createUuidV7();

    expect(id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/,
    );
  });

  test("keeps lexical order for sequential ids generated by the library", () => {
    const ids = Array.from({ length: 20 }, () => createUuidV7());

    expect([...ids].sort()).toEqual(ids);
  });
});
